apiVersion: v1
kind: Service
metadata:
  name: oip-es-prod
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: oip-es-prod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oip-es-prod
spec:
  selector:
    matchLabels:
      app: oip-es-prod
  replicas: 1
  template:
    metadata:
      labels:
        app: oip-es-prod
    spec:
      containers:
      - name: oip-es-prod
        image: socialalphaoip/elasticsearch-microservice:prod
        ports:
        - containerPort: 8080
        env:
          - name: HASURA_GRAPHQL_URL
            value: http://oip-hasura-prod/v1/graphql
          - name: HASURA_GRAPHQL_ADMIN_SECRET
            value: 1SocialAlpha
---