apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: oip-es-prod-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - oip-es-prod.k8s.jaagalabs.com
    secretName: oip-es-prod-tls
  rules:  
  - host: oip-es-prod.k8s.jaagalabs.com
    http:
      paths:
      - backend:
          serviceName: oip-es-prod
          servicePort: 80